# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

name: Test

on: [push]

jobs:
  FlatpakYukleyici:
    name    : Test
    runs-on : ubuntu-latest

    steps:
      - name: Depo Kontrolü
        uses: actions/checkout@v3

      - name: Güncelleme Kontrol Et
        id  : guncelleme_var_mi
        run : |
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | cat